name: CI/CD Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  build-and-deploy:
    name: Build and Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest

      - name: Set Up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.23.6'

      - name: Setup Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          export KUBECONFIG=kubeconfig

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/deployment.yml
          kubectl apply -f kubernetes/service.yml

      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get services

      - name: Notify Success
        uses: rjstone/discord-webhook-notify@v1
        wi`th:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          content: "✅ Deployment succeeded for Node.js application!"

    if: success() || failure()
